<?php
require_once( get_stylesheet_directory() . '/wordpress/initial_data.php' );
// Load scripts
function load_vue_scripts() {

    if (IS_PRODUCTION) {

    } else {
        wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			'http://localhost:'. VUE_PORT .'/app.js',
			array(),
			false,
			true
		);

		
	}
	register_endpoints();
	register_initial_data();

	wp_enqueue_script('themint/app.js');
}
add_action('wp_enqueue_scripts', 'load_vue_scripts', 100);