<?php
require_once( get_stylesheet_directory() . '/wordpress/initial_data.php' );
// Load scripts
function load_vue_scripts() {
	global $options;

    if (IS_PRODUCTION) {
		$files = $options['files'];
		wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			get_stylesheet_directory_uri() . '/dist/' . $files['app']['js'],
			array(),
			false,
			true
		);
		wp_register_script( // the app build script generated by Webpack.
			'themint/vendor.js',
			get_stylesheet_directory_uri() . '/dist/' . $files['chunk-vendors']['js'],
			array(),
			false,
			true
		);
		wp_enqueue_style( 
			'themin/app.css',
			get_stylesheet_directory_uri() . '/dist/' . $files['app']['css']
		);
		wp_enqueue_style( 
			'themin/vendor.css',
			get_stylesheet_directory_uri() . '/dist/' . $files['chunk-vendors']['css']
		);

    } else {
        wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			'http://localhost:'. VUE_PORT .'/app.js',
			array(),
			false,
			true
		);

		
	}
	register_endpoints();
	register_initial_data();

	wp_enqueue_script('themint/app.js');
	wp_enqueue_script('themint/vendor.js');
}
add_action('wp_enqueue_scripts', 'load_vue_scripts', 100);